# Generated by Django 2.1.5 on 2019-09-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teams',
            table='TeamsDB',
        ),
    ]
