# Generated by Django 2.1.5 on 2019-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0002_auto_20190929_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grp', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'TeamsDB',
            },
        ),
    ]
