# Generated by Django 2.1.5 on 2019-09-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0003_groups'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groups',
            table='Groups',
        ),
    ]
