# Generated by Django 2.1.5 on 2019-09-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0004_auto_20190929_2340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groups',
            table='Groupsnames',
        ),
    ]
