# Generated by Django 2.1.5 on 2019-09-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0005_auto_20190929_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
